---

- name: Pull latest mysql container image
  docker_image:
    name: "{{ zabbix.mysql.container_image }}"
    tag: "{{ zabbix.mysql.container_image_tag | default(omit) }}"
    source: pull
    force_source: true
  when: zabbix is defined

- name: Setup mysql container volume
  docker_volume:
    name: mysql_data
    state: present
  when: zabbix is defined

- name: Setup mysql container container
  docker_container:
    name: zabbix_mysql
    image: "{{ zabbix.mysql.container_image }}:{{ zabbix.mysql.container_image_tag | default('latest') }}"
    state: started
    network_mode: host
    restart_policy: "{{ zabbix.mysql.restart_policy | default(omit) }}"
    env:
      MYSQL_ROOT_PASSWORD: "{{ zabbix.mysql.password }}"
    volumes:
      - "mysql_data:/var/lib/mysql"
  when: zabbix is defined
