---

- include_tasks: server_proxy_common.yml

- name: Pull latest zabbix server container image
  docker_image:
    name: "{{ zabbix.server.container_image }}"
    tag: "{{ zabbix.server.container_image_tag | default(omit) }}"
    pull: yes
    force: yes
  when: zabbix is defined

- name: Setup zabbix server container
  docker_container:
    name: "{{ zabbix.server.container_name }}"
    image: "{{ zabbix.server.container_image }}:{{ zabbix.server.container_image_tag | default('latest') }}"
    state: started
    network_mode: host
    env: "{{ zabbix.server.envs }}"
    restart_policy: "{{ zabbix.server.restart_policy | default(omit) }}"
    volumes:
      - /etc/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /etc/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - /etc/zabbix/modules:/var/lib/zabbix/modules
      - /etc/zabbix/enc:/var/lib/zabbix/enc
      - /etc/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys
      - /etc/zabbix/ssl/certs:/var/lib/zabbix/ssl/certs
      - /etc/zabbix/ssl/keys:/var/lib/zabbix/ssl/keys
      - /etc/zabbix/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca
      - /etc/zabbix/snmptraps:/var/lib/zabbix/snmptraps
      - /etc/zabbix/mibs:/var/lib/zabbix/mibs
      - /etc/zabbix/odbc.ini:/etc/odbc.ini
  when: zabbix is defined
